// Generated by CoffeeScript 1.4.0

/* jslint nomen: true, plusplus: true, vars: true, indent: 2, node: true
*/


(function() {
  "use strict";

  var $, CreateFakeApp, ECT, Faker, S3Config, S3CreateNewAppsJSONFile, S3UpdateAppsJSON, S3upload, app, appdir, apps, apps_file_url, apps_filename, client, ectRenderer, exampleapp, express, fs, knox, port, uniqueId,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  express = require('express');

  $ = require('jquery');

  ECT = require('ect');

  fs = require('fs');

  Faker = require('Faker');

  require('js-yaml');

  S3Config = require('./config/S3.yml');

  knox = require('knox');

  client = knox.createClient(S3Config);

  appdir = '/apps/';

  apps_filename = 'apps.json';

  apps_file_url = 'https://' + S3Config['bucket'] + '.s3.amazonaws.com' + appdir + apps_filename;

  console.log("apps.json is: " + apps_file_url);

  port = process.env.PORT || 5000;

  /* MUST Move these Methods to Lib in Next sprint
  */


  uniqueId = function(length) {
    var id;
    if (length == null) {
      length = 18;
    }
    id = '_TEST';
    while (id.length < length) {
      id += Math.random().toString(36).substr(2);
    }
    return id.substr(0, length);
  };

  CreateFakeApp = function() {
    var exampleapp, _ref;
    exampleapp = require('./public/app-example.json');
    exampleapp['Id'] = uniqueId(18);
    exampleapp['Mandatory__c'] = (_ref = Math.random() < 0.5) != null ? _ref : {
      "true": false
    };
    exampleapp['Name'] = Faker.random.bs_buzz();
    exampleapp['Description__c'] = Faker.Lorem.sentence();
    return exampleapp;
  };

  S3upload = function(filename, jsonstr) {
    var req;
    req = client.put(appdir + filename, {
      'Content-Length': jsonstr.length,
      'Content-Type': 'application/json',
      'x-amz-acl': 'public-read'
    });
    req.on('response', function(res) {
      if (200 === res.statusCode) {
        return console.log('saved to %s', req.url);
      }
    });
    return req.end(jsonstr);
  };

  S3UpdateAppsJSON = function(newapp) {
    var existing_apps;
    existing_apps = [];
    return $.getJSON(apps_file_url, function(apps) {
      var app, appsnew, _i, _len, _ref;
      console.log("There are " + apps.length + " Apps");
      if (apps.length > 0) {
        for (_i = 0, _len = apps.length; _i < _len; _i++) {
          app = apps[_i];
          existing_apps.push(app['Id']);
          if (app['Id'] === newapp['Id']) {
            app = newapp;
          }
        }
      } else {
        S3CreateNewAppsJSONFile(newapp);
      }
      if (_ref = newapp['Id'], __indexOf.call(existing_apps, _ref) >= 0) {
        return S3upload(apps_filename, JSON.stringify(apps));
      } else {
        console.log("*NEW* App: " + newapp['Id']);
        console.dir(existing_apps);
        apps.push(newapp);
        console.log("Number of apps with *New* App: " + apps.length);
        appsnew = apps;
        return S3upload(apps_filename, JSON.stringify(appsnew));
      }
    }).error(function() {
      console.log('error fetching apps.json ... CREATE it!');
      return S3CreateNewAppsJSONFile(newapp);
    });
  };

  S3CreateNewAppsJSONFile = function(newapp) {
    var apps;
    apps = [];
    apps.push(newapp);
    return S3upload(apps_filename, JSON.stringify(apps));
  };

  exampleapp = require('./public/app-example.json');

  apps = S3UpdateAppsJSON(exampleapp);

  /* The Mini Express App
  */


  app = module.exports = express();

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express["static"](__dirname + '/public'));
    app.use(express["static"](__dirname + '/spec'));
    app.use(express["static"](__dirname + '/lib'));
    return app.use(express["static"](__dirname + '/apps'));
  });

  ectRenderer = ECT({
    watch: true,
    root: __dirname + '/views'
  });

  app.engine('.html', ectRenderer.render);

  app.get('/', function(req, res) {
    return res.render('layout.html', {
      title: 'Hello!'
    });
  });

  app.get('/upload', function(req, res) {
    return res.render('uploadform.html', {
      title: 'Basic Uploader Form'
    });
  });

  app.post('/upload', function(req, res, next) {
    var newapp;
    newapp = JSON.parse(req.body.json);
    console.log('\n # # # # # # # # # \n');
    console.log(newapp);
    console.log('\n # # # # # # # # # \n');
    S3UpdateAppsJSON(newapp);
    return res.end();
  });

  app.get('/fakeapp', function(req, res) {
    exampleapp = CreateFakeApp();
    return res.send(exampleapp);
  });

  app.get('/tdd', function(req, res) {
    return res.render('SpecRunner.html', {
      title: 'Test Runner'
    });
  });

  app.get('/s3url', function(req, res) {
    return res.send({
      url: 'http://' + S3.S3Config.bucket + '.s3.amazonaws.com/'
    });
  });

  app.get('/appsjson', function(req, res) {
    return $.getJSON(apps_file_url, function(json) {
      return res.send(json);
    });
  });

  app.listen(port);

  console.log("Express started on port " + port);

}).call(this);
